DROP TABLE IF EXISTS names;

CREATE TABLE IF NOT EXISTS names (
	id TEXT NOT NULL PRIMARY KEY,
	name TEXT NOT NULL,
	owner TEXT NOT NULL,
	texts TEXT,
	addresses TEXT,
	contenthash TEXT,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);