name = "server"
main = "src/index.ts"
compatibility_date = "2023-10-25"
compatibility_flags = [ "nodejs_compat" ]


d1_databases = [
{ binding = "DB", name = "river", database_id = "c2644ec6-1700-4d5c-9d25-3ba84092fc11" }
]

[vars]
PRIVATE_KEY="a3ab6d009ee8e6f1f89423857bf6f69149239dc71cfba07996bd50f483d7d3b1"

